### ISSUE TITLE
Query: Task List

### ISSUE THREAD

**Issue by smitpatel** [aspnet/EntityFrameworkCore#14630]
To re-implement parts
- [x] 1. Null semantics before second level cache
- [ ] 2. Parameter nullability based SQL reduction
- [ ] 3. Removal of redundant explicit cast to same type
- [x] 4. Value to search condition transformation and vice-versa
- [ ] 5. is operator optimization to discriminator
- [x] 6. Nav Expansion
- [x] 7. `==` between anon types in where should get de-constructed? (#14672 )
- [x] 8. Parameter being null converted to `IS NULL`
- [ ] 9. Eliminate InvocationExpression when lambda expression. [Like this](https://github.com/re-motion/Relinq/blob/develop/Core/Parsing/ExpressionVisitors/Transformation/PredefinedTransformations/InvocationOfLambdaExpressionTransformer.cs)
- [x] 10. Cross Join
- [x] 11. Join
~- [ ] 12. EntityEqualityRewrite~ #15588"
- [x] 13. Subquery pushdown
- [x] 14. Subquery lifting
- [ ] 15. Reduce constant based comparison/conditionals in SQL tree
- [x] 16. Subquery InExpression
- [x] 17. Tracking behavior
- [x] 18. DbFunction support
- [x] 19. Include
- [ ] 20. Owned entities support
- [x] 21. Discriminator/Inheritance support
- [x] 22. Async query support
- [ ] 23. Concurrency detection
- ~[ ] 24. Verify Exceptions~ #15751

**Comment by smitpatel** [comment]
Closing this as most of the things here have own tracking issues.
