### ISSUE TITLE
Query work for in-memory provider

### ISSUE THREAD

**Issue by ajcvickers** [aspnet/EntityFrameworkCore#16963]
- [x] Reference Include
- [x] Collection Include
- [x] Collection in projection @smitpatel 
- [x] Single non-scalar result in projection @smitpatel 
- [x] Translate Owned navigation properties in query @smitpatel
- [x] investigate/fix failures in FiltersInheritanceInMemoryTest test suite
- [x] Re-enable non-query tests @smitpatel
  - [x] GraphUpdatesInMemoryTest
  - [x] ProxyGraphUpdatesInMemoryTest
  - [x] LoadInMemoryTest
  - [x] InMemoryComplianceTest @smitpatel
  - [x] FixupTest.Collection_nav_props_remain_fixed_up_after_manual_fixup_and_DetectChanges @smitpatel
  - [x] QueryRewrite: enable inmemory tests failing with NRE and "Nullable object must have a value" See #15343 @maumar
- [x] InMemory: Reading value from server may need to apply default. See #16575 @maumar
- [x] Inheritance
- [X] Spatial @bricelam
~- [ ] ValueComparer.Snapshot() results~ #14042

Test Failures
- [x] Include18_3_3 @smitpatel
- [x] Join_flattening_bug_4539 @smitpatel
- [x] Too many results @maumar - needs core changes, filed #17531 to track this

Queryable methods pending
- [x] Cast P4 Implemented by @smitpatel in https://github.com/aspnet/EntityFrameworkCore/commit/9f202066018f67efdb56c87c0995ab39f17ae74c
- [x] Concat/Except/Intersect/Union P6 @roji
- [x] DefaultIfEmpty P1 @smitpatel
- [x] GroupBy P5 @smitpatel
- [x] OfType/is P3 @ajcvickers
~- [ ] Reverse P7~ #17388
- [x] SelectMany P2 @smitpatel

**Comment by AndriySvyryd** [comment]
Surely one of the assignees will do this work in time for 3.0.0

**Comment by ajcvickers** [comment]
@AndriySvyryd Surely.

**Comment by ajcvickers** [comment]
I'm going to try doing this...

**Comment by smitpatel** [comment]
@ajcvickers has volunteered to do all the work for InMemory query 🎉

**Comment by smitpatel** [comment]
Can you also make sure to update the issue numbers to this one in code base comments for skipped tests?

**Comment by dhhunter** [comment]
var blogInfo = await context.Blogs
                .Where(x => x.Id == 1)
                .Include(x => x.Posts)
                .Select(x => new BlogInfo(x.Url, x.Posts.Count))
                .SingleAsync();

Test method EfCoreSample.BlogTests.CanGetBlogAsInfo threw exception: 
System.NotImplementedException: The method or operation is not implemented.
    at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.VisitNew(NewExpression newExpression)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Translate(InMemoryQueryExpression queryExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.SingleAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at EfCoreSample.BlogTests.CanGetBlogAsInfo() in C:\Users\dhunter\source\repos\ConfigSample\EfCoreSample\BlogTests.cs:line 101
   at EfCoreSample.BlogTests.CanGetBlogAsInfo() in C:\Users\dhunter\source\repos\ConfigSample\EfCoreSample\BlogTests.cs:line 108
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)

**Comment by jsheetzati** [comment]
Seeing this error on a simple FirstOrDefaultAsync
```
Appointment appointment = await _context.Appointment.FirstOrDefaultAsync(a =>
      a.Id == request.AppointmentId &&
      a.AppointmentStatus == AppointmentStatus.Pending);
```

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , ValueBuffer )
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryShapedQueryCompilingExpressionVisitor.AsyncQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at
```

**Comment by julielerman** [comment]
Hi guys,. I want to make sure I'm interpreting this correctly. The check mark in the original post (e.g. for collection include) means that it's done and I should be seeing the effect in the nightly build right? I grabbe the nightly build of the SDK a few days ago (dotnet --version says I have 3.0.100-preview9-013817) and I'm referencing 3.0.0-preview9.19413.1 of the inmemory package. yet I''m still getting the error on the include(collection property) that I was getting with preview7 and preview8.  What should I expect? I"m supposed to be writing your teams' article for Code Mag and it's really hard with not knowing what is working and what is not... and what is just some fix coming which relies on me doing just the right search on github. Thanks.

**Comment by dhhunter** [comment]
Wow a celebrity poster!

I am using InMemory 19415.13 and a simple query like:

var blog = await context.Blogs
                .Include(x => x.Posts)
                .SingleAsync(x => x.Id == 1);

Is working fine.  However, more complex queries such as:

            var blog = context.Blogs
                .Where(x => x.Id == 1)
                .Include(x => x.Posts)
                .Select(b => new BlogDetails(b.Id, b.Url, b.Posts
                    .Select(p => new PostInfo(p.Id, p.Title))))
                .Single();

            var blogInfo = await context.Blogs
                .Where(x => x.Id == 1)
                .Include(x => x.Posts)
                .Select(x => new BlogInfo(x.Id, x.Url, x.Posts.Count()))
                .SingleAsync();

Still do not work as Select and Count are NotImplemented on a Reference Collection Property.

Count actually works if you use the nasty Object Initializer Syntax.

            var blogInfo = await context.Blogs
                .Where(x => x.Id == 1)
                .Include(x => x.Posts)
                .Select(x => new BlogInfo()
                {
                    Url = x.Url,
                    NumberOfPosts = x.Posts.Count
                })
                .SingleAsync();

What are you trying to do?

**Comment by smitpatel** [comment]
@dhhunter -
I added  2 more items for collection in projection & single non scalar in projection. (which are related but slightly different from include.
For your queries,
1. Works
2. Since you are composing over Posts collection, it goes in collection in projection work-item.
3.  Should be working. Can you file new issue with exception message?
4. 3 & 4 are equivalent. If you use `Count` member on list rather than Count() method.

**Comment by julielerman** [comment]
am I referencing the package incorrectly? Where are you getting your version # from? 
@smitpatel  there are docs on how to download the latest SDK but not anything on how to actually use the nightly builds of EF Core bits.

**Comment by smitpatel** [comment]
https://github.com/aspnet/AspNetCore/blob/master/docs/DailyBuilds.md

**Comment by julielerman** [comment]
thanks yes I have done that. So what about referencing the package...just don't put any version in at all?

**Comment by smitpatel** [comment]
`3.0.0-*` should get you the latest daily.

**Comment by julielerman** [comment]
ah ok. I got lates with 3.0.0-preview9.* but I'll trim it back. Thought I'd tried that last night. THANKS.

**Comment by julielerman** [comment]
Not sure if this is included in "Translate Owned navigation properties in query" so thought I would mention just in case. If Include points to a navigation property  (not owned) and the target entity of that property has any owned entities, it is also failing. I did a lot of "one of these things is not like the other" before narrowing it down. If you need a mini repro let me know.
Here is the first bits from the stack trace:
Error Message:
    System.NullReferenceException : Object reference not set to an instance of an object.
    Stack Trace:
       at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.EntityProjectionExpression.BindProperty(IProperty property)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryExpressionTranslatingExpressionVisitor.BindProperty(EntityProjectionExpression entityProjectionExpression, IProperty property)
   at

**Comment by smitpatel** [comment]
I will probably pick up larger items in the list. I am looking at all fancy projections right now. Owned support and GroupBy is next on the list. If you are thinking about working on any of it, ping me, we can distribute the work.

**Comment by julielerman** [comment]
Wow @smitpatel all the things checked off!! BRAVO! 🥇

**Comment by dhhunter** [comment]
Yay!  Thank you very much @smitpatel, I really love seeing many red unit tests turning green!!!

Unfortunately, not all of them turned green!  So here we go:

`
var blog = context.Blogs
	.Where(x => x.Id == 1)
	.Include(x => x.Posts)
	.Select(b => new BlogDetailsWithCount(b.Id, b.Url, b.Posts
		.Select(p => new PostInfo(p.Id, p.Title)).ToList(), b.Posts.Count))
	.Single();
				
Test method EfCoreSample.BlogTests.CanGetBlogAsDetailsWithCount threw exception: 
System.InvalidCastException: Unable to cast object of type 'System.Linq.Expressions.NewExpression' to type 'System.Linq.Expressions.MethodCallExpression'.
    at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryExpression.AddSubqueryProjection(ShapedQueryExpression shapedQueryExpression, Expression& innerShaper)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.VisitNew(NewExpression newExpression)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Translate(InMemoryQueryExpression queryExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Single[TSource](IQueryable`1 source)
   at EfCoreSample.BlogTests.CanGetBlogAsDetailsWithCount() in C:\Users\dhunter\source\repos\ConfigSample\EfCoreSample\BlogTests.cs:line 242
   at EfCoreSample.BlogTests.CanGetBlogAsDetailsWithCount() in C:\Users\dhunter\source\repos\ConfigSample\EfCoreSample\BlogTests.cs:line 252
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)
`

`
var blogInfo = await context.Blogs
	.Where(x => x.Id == 1)
	.Include(x => x.Posts)
	.Select(x => new BlogInfo(x.Id, x.Url, x.Posts.Count()))
	.SingleAsync();
				
Test method EfCoreSample.BlogTests.CanGetBlogAsInfoByCtorCountExtensionMethod threw exception: 
System.InvalidCastException: Unable to cast object of type 'System.Linq.Expressions.NewExpression' to type 'System.Linq.Expressions.MethodCallExpression'.
    at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryExpression.AddSubqueryProjection(ShapedQueryExpression shapedQueryExpression, Expression& innerShaper)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.VisitNew(NewExpression newExpression)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Translate(InMemoryQueryExpression queryExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.SingleAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at EfCoreSample.BlogTests.CanGetBlogAsInfoByCtorCountExtensionMethod() in C:\Users\dhunter\source\repos\ConfigSample\EfCoreSample\BlogTests.cs:line 79
   at EfCoreSample.BlogTests.CanGetBlogAsInfoByCtorCountExtensionMethod() in C:\Users\dhunter\source\repos\ConfigSample\EfCoreSample\BlogTests.cs:line 86
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)
`

`  
var blogInfo = await context.Blogs
	.Where(x => x.Id == 1)
	.Include(x => x.Posts)
	.Select(x => new BlogInfo(x.Id, x.Url, x.Posts.Count))
	.SingleAsync();
				
Test method EfCoreSample.BlogTests.CanGetBlogAsInfoByCtorCountProperty threw exception: 
System.InvalidCastException: Unable to cast object of type 'System.Linq.Expressions.NewExpression' to type 'System.Linq.Expressions.MethodCallExpression'.
    at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryExpression.AddSubqueryProjection(ShapedQueryExpression shapedQueryExpression, Expression& innerShaper)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.VisitNew(NewExpression newExpression)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Translate(InMemoryQueryExpression queryExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.SingleAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at EfCoreSample.BlogTests.CanGetBlogAsInfoByCtorCountProperty() in C:\Users\dhunter\source\repos\ConfigSample\EfCoreSample\BlogTests.cs:line 94
   at EfCoreSample.BlogTests.CanGetBlogAsInfoByCtorCountProperty() in C:\Users\dhunter\source\repos\ConfigSample\EfCoreSample\BlogTests.cs:line 101
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)
`

` 
var blogInfo = await context.Blogs
	.Where(x => x.Id == 1)
	.Include(x => x.Posts)
	.Select(BlogInfoMapper.Map)
	.SingleAsync();

public class BlogInfoMapper
{
	public static Expression<Func<Blog, BlogInfo>> Map => x => new BlogInfo(x.Id, x.Url, x.Posts.Count);
}
	
Test method EfCoreSample.BlogTests.CanGetBlogAsInfoByMethodCtorMap threw exception: 
System.InvalidCastException: Unable to cast object of type 'System.Linq.Expressions.NewExpression' to type 'System.Linq.Expressions.MethodCallExpression'.
    at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryExpression.AddSubqueryProjection(ShapedQueryExpression shapedQueryExpression, Expression& innerShaper)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.VisitNew(NewExpression newExpression)
   at System.Linq.Expressions.NewExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Visit(Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryProjectionBindingExpressionVisitor.Translate(InMemoryQueryExpression queryExpression, Expression expression)
   at Microsoft.EntityFrameworkCore.InMemory.Query.Internal.InMemoryQueryableMethodTranslatingExpressionVisitor.TranslateSelect(ShapedQueryExpression source, LambdaExpression selector)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.ExpressionVisitor.Visit(Expression node)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass12_0`1.<ExecuteAsync>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQueryCore[TFunc](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ExecuteAsync[TSource,TResult](MethodInfo operatorMethodInfo, IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.SingleAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at EfCoreSample.BlogTests.CanGetBlogAsInfoByMethodCtorMap() in C:\Users\dhunter\source\repos\ConfigSample\EfCoreSample\BlogTests.cs:line 148
   at EfCoreSample.BlogTests.CanGetBlogAsInfoByMethodCtorMap() in C:\Users\dhunter\source\repos\ConfigSample\EfCoreSample\BlogTests.cs:line 155
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)
`

**Comment by smitpatel** [comment]
@dhhunter - Thanks for reporting this. I have filed #17620 to track it. The issue is because of new BlogInfo { } in projection. If you select components of it and then construct object on client side then it should work.

**Comment by brenwebber** [comment]
I'm getting this error, but in slightly different a different situation. I want to create a simpler sample to upload, but no time at the moment.

Scenario: Fetching a Parent-ChildCollection and projecting to DTO Parent-ChildAggregate with a nested Parent.OwnedEntityProperty with
