### ISSUE TITLE
Query: List of refactoring ideas

### ISSUE THREAD

**Issue by anpete** [aspnet/EntityFrameworkCore#7520]
Brain dump of potential refactorings in the query pipeline captured from a discussion today with @smitpatel and @maumar.

~- [ ] Immutable SelectExpression via facade/visitors~ Not worth
- [x] AliasExpressions everywhere or ColumnRefExpressions for referentially consistent SQL tree. (@smitpatel) #7950 
- [x] Include via QueryModel (@anpete) #7974 
~- [ ] Include/nav-prop synergy via early QM rewrites.~
~- [ ] Immutable QueryModel~
~- [ ] First-class * expression (perhaps via exploded column containment idea)~ We do not have * projection for now. We can introduce it in future.
- [x] SearchConditionTranslatingVisitor rewrite (#7554)
- [x] Subquery lifting at query model level (#7613)
- [x] Consistentize use of visitors/extension nodes, VisitChildren etc.
- [x] Apply CompositePredicateExpressionVisitor to other parts of the SelectExpression (#7608)
~- [ ] Evaluate ClientEval flags.~ We do not have client eval flag. 
- [x] Investigate NullConditionalExpression processing in RequiresMaterializationExpressionVisitor (#7746)
- [ ] clean up Nav + Entity Equality rewriting visitors (#7773)
- [ ] Clean up & Improve QueryOptimizer (#7831)
- [ ] Avoid unnecessary pushdown of subqueries (#8094)
~- [ ] Investigate DRYing up null expressions (NullableExpression and NullConditionalExpression)~ Removed NullableExpression
~- [ ] Clean-up logic around RemoveConvert (#8318)~ Nomore RemoveConvert
- [ ] Rename and clean-up EQMV.OptimizeQueryModel
- [x] log contents of compiled code (#9455)

@smitpatel, @maumar Feel free to add more detail here.

**Comment by tuespetre** [comment]
How about the `RelationalEntityQueryableExpressionVisitor` vs `MemberAccessBindingExpressionVisitor` thing? Not the fact that they are two separate visitors (they have different purposes) but the fact that `RelationalEntityQueryableExpressionVisitor` seems to be overstepping its bounds by being responsible for adding things to `SelectExpression`s. I ask because as I am writing and fixing tests for some complex `GroupBy` queries, I'm seeing that `MemberAccessBindingExpressionVisitor` is going to need to be able to bind grouping keys, which means they need to be present in the `SelectExpression`, which means there is going to have to be some duplicate grouping key processing logic going on between the two visitors as it stands.

**Comment by smitpatel** [comment]
TableExpressionBase Alias & QuerySource both are nullable & settable. Review.

**Comment by smitpatel** [comment]
`FromSqlExpression.Arguments` is not a collection property, just `Expression`. Review property name.

**Comment by smitpatel** [comment]
Eliminate `IsProjectStar` by introducing an expression in SelectExpression.Projection representing star projection.

**Comment by tuespetre** [comment]
I have an idea to simplify/streamline a good chunk of code around shaped queries, parameter injection, and similar (possibly includes but I'm not up to speed on how that feature has been evolving.) Basically, represent all of these 'special method call expressions' as reducible extension expressions that carry appropriate metadata with them: for instance, `ShapedQueryExpression`, which carries with it a `SelectExpression` and a `Shaper`, and when `Reduce()` is called, it reduces down to the appropriate `MethodCallExpression`.

By doing this, the codebase can move away from a lot of the trickiness of digging into `MethodCallExpressions` to inspect their methods and arguments and perform surgery on them, and towards a more 'expressive' way that encapsulates that kind of logic in one place. 

I think the code will better explain itself so I will submit a PR to demonstrate the idea using `ShapedQueryExpression`.

**Comment by anpete** [comment]
This sounds good. We have discussed changes like this internally, too. Look forward to the PR.

**Comment by tuespetre** [comment]
More ideas for building a richer expression tree:

- Instead of having `SqlTranslatingExpressionVisitor` return `null` and have a `ClientEvalPredicate` property, have it return expressions that can be used with pattern matching for a more functional processing style:
    - `SqlTranslatableExpression`
    - `SqlUntranslatableExpression`
    - `SqlPartiallyTranslatableExpression` with `TranslatableExpression` and `UntranslatableExpression` properties to represent an `AndAlso` expression with a translatable side and an untranslatable side
- Perform some kind of pre-processing that wraps certain types of expression patterns into first-class extension expressions in order to eliminate some of the need to constantly refer back to the query model visitor for member and method binding, for example:
    - `EntityReferenceExpression`
    - `MappedPropertyExpression`
    - `UnmappedPropertyExpression`

**Comment by ajcvickers** [comment]
@anpete Punt the rest of this for 2.0? /cc @divega

**Comment by anpete** [comment]
@ajcvickers Yeah, I don't think we ever need this bug in a milestone, rather we can create specific individual issues when we decide to work on something.

**Comment by smitpatel** [comment]
At present all queries return enumerable which causes us to convert single result to sequence. Improve the contract so that we don't have to do special processing and we can just return single result.

**Comment by smitpatel** [comment]
Pulling this into 3.0 since we should either finish this with #12795 or close this.

**Comment by smitpatel** [comment]
We have done whatever was relevant here in new pipeline. Closing as fixed.
