### ISSUE TITLE
RevEng: Clean up internal code

### ISSUE THREAD

**Issue by bricelam** [aspnet/EntityFrameworkCore#8853]
A few ideas:
- [ ] Move checks for default constraint names in CSharpDbContextGenerator to ScaffoldingModelFactory
- [ ] Better variable and parameter names
- [x] Rename ModelScaffolder to ReverseEngineeringScaffolder OR merge it into DatabaseOperations
- [x] Decouple RelationalScaffoldingModelFactory from IDatabaseModelFactory
- [ ] Use resources (issue #8599)
- [x] Clean up IModel annotations (issue #8689)
- [x] Remove DbDataReaderExtension (issue #8712)
- [x] Remove TableSelectionSet
- [ ] Merge code which does similar things in Migrations (issue #1671)
  - CSharpUtilities cf CSharpHelper
  - code that transforms directory paths into namespaces
  - code for GenerateAnnotations including GenerateFluentApiForAnnotation
  - DbContext writer does not generate namespaces for custom types
- [ ] Uniquification is done twice in `CSharpUtilities` and in `CSharpUniqueNamer`. We should rationalize this and figure out how configurable candidate naming, ensuring valid C# identifier, storing the names so that another name used in the same context clashes, and pluralization/singularization fits in to that process (see #8989).
- [x] Use IOperationsReporter and vanilla Logging (issue #8686)
- [x] Remove IRelationalTypeMapper dependency in RelationalScaffoldingModelFactory (use IScaffoldingTypeMapper)
- [x] Remove protected dependency properties on internal services
- [x] Remove ServiceCollection.AddScaffolding() extension method (update tests to build the full design-time service provider)
- [x] Decouple IScaffoldingCodeGenerator form I/O (see [this comment](https://github.com/aspnet/EntityFrameworkCore/pull/10356#issuecomment-346412414))

**Comment by smitpatel** [comment]
`TableSelectionSet` being removed in #9315

**Comment by ajcvickers** [comment]
Closing since we've done what we are going to do here. PRs still welcome for good cleanup.
